### ISSUE TITLE
Add the following lines to gitignore

### ISSUE THREAD

**Issue by jgalan** [sebhoof/SolarAxionFlux#2]
I would have commit it myself but I had no rights access. I think it would be good to remove the library products from `git status` 

Adding these lines to `.gitignore`
```
# Directories
bin
lib/libaxionflux.s*
```

**Comment by sebhoof** [comment]
Sure, I've done this [in the latest commit](https://github.com/sebhoof/SolarAxionFlux/commit/1867458ae49e5c6cac0218a7e1149e2280439790) and sent you an invitation to the project.
